services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - redis
      - celery

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A recept worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A recept beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis