# Generated by Django 5.0.3 on 2024-11-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_options_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calories',
            options={'verbose_name': 'Калорийность', 'verbose_name_plural': 'Калорийности'},
        ),
        migrations.AlterModelOptions(
            name='recipecategory',
            options={'verbose_name': 'Категория рецепта', 'verbose_name_plural': 'Категории рецептов'},
        ),
        migrations.AlterModelOptions(
            name='recipecomment',
            options={'verbose_name': 'Комментарий к рецепту', 'verbose_name_plural': 'Комментарии к рецептам'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Ингредиент рецепта', 'verbose_name_plural': 'Ингредиенты рецептов'},
        ),
        migrations.AlterModelOptions(
            name='recipelike',
            options={'verbose_name': 'Лайк рецепта', 'verbose_name_plural': 'Лайки рецептов'},
        ),
        migrations.AlterModelOptions(
            name='recipestep',
            options={'verbose_name': 'Шаг рецепта', 'verbose_name_plural': 'Шаги рецептов'},
        ),
        migrations.AlterModelOptions(
            name='userrecipes',
            options={'verbose_name': 'Рецепт пользователя', 'verbose_name_plural': 'Рецепты пользователей'},
        ),
    ]
