# Generated by Django 5.0.3 on 2024-11-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_calories_options_alter_recipecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecomment',
            name='status',
            field=models.CharField(choices=[('На модерации', 'На модерации'), ('Опубликован', 'Опубликован'), ('Отклонят', 'Отклонят')], default='На модерации', max_length=50),
        ),
    ]
