# Generated by Django 5.0.3 on 2024-11-14 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calories',
            name='carbohydrates',
            field=models.IntegerField(blank=True, null=True, verbose_name='Углеводы'),
        ),
        migrations.AlterField(
            model_name='calories',
            name='fat',
            field=models.IntegerField(blank=True, null=True, verbose_name='Жиры'),
        ),
        migrations.AlterField(
            model_name='calories',
            name='protein',
            field=models.IntegerField(blank=True, null=True, verbose_name='Белки'),
        ),
        migrations.AlterField(
            model_name='calories',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calories_info', to='recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='adversting_text',
            field=models.CharField(blank=True, max_length=500, verbose_name='Рекламирующий текст'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Публичность'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='number_of_servings',
            field=models.IntegerField(verbose_name='Количество персон'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на главную фотографию '),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.CharField(default='На модерации', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='status_site',
            field=models.CharField(blank=True, max_length=50, verbose_name='Статус на сайте'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time_of_cooking',
            field=models.IntegerField(verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipecategory',
            name='category_name',
            field=models.CharField(max_length=255, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='recipecategory',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='recipecomment',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='recipecomment',
            name='status',
            field=models.CharField(choices=[('На модерации', 'На модерации'), ('Опубликован', 'Опубликован'), ('Отклонят', 'Отклонят')], default='На модерации', max_length=50, verbose_name='Статус комментария'),
        ),
        migrations.AlterField(
            model_name='recipecomment',
            name='text',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='recipecomment',
            name='text_of_moderation',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ответ модератора'),
        ),
        migrations.AlterField(
            model_name='recipecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient_name',
            field=models.CharField(max_length=500, verbose_name='Название ингредиентов'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='measurement_name',
            field=models.CharField(max_length=500, verbose_name='Измерение'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.CharField(max_length=500, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='recipelike',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Лайк на рецепт'),
        ),
        migrations.AlterField(
            model_name='recipelike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='photo_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на фото шага'),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='step_number',
            field=models.IntegerField(verbose_name='Номер шага'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], default='Мужской', max_length=20, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='Пользователь', max_length=50, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='userrecipes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='userrecipes',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='userrecipes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.user', verbose_name='Пользователь'),
        ),
    ]
