# Generated by Django 5.0.3 on 2024-11-14 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='ingredient_name',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='measurement_name',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient', verbose_name='Ингредиент'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_name',
            field=models.CharField(choices=[('шт', 'шт'), ('л', 'л'), ('л', 'л'), ('мл', 'мл'), ('гр', 'гр'), ('чайная ложка', 'чайная ложка'), ('столовая ложка', 'столовая ложка'), ('кг', 'кг'), ('мг', 'мг')], default='гр', max_length=50, verbose_name='Измерение'),
        ),
    ]
