# Generated by Django 5.0.3 on 2024-11-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_remove_recipeingredient_ingredient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('шт', 'шт'), ('л', 'л'), ('мл', 'мл'), ('гр', 'гр'), ('чайная ложка', 'чайная ложка'), ('столовая ложка', 'столовая ложка'), ('кг', 'кг'), ('мг', 'мг')], default='гр', max_length=50, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_name',
            field=models.CharField(choices=[('шт', 'шт'), ('л', 'л'), ('мл', 'мл'), ('гр', 'гр'), ('чайная ложка', 'чайная ложка'), ('столовая ложка', 'столовая ложка'), ('кг', 'кг'), ('мг', 'мг')], default='гр', max_length=50, verbose_name='Измерение'),
        ),
    ]
