# Generated by Django 5.0.3 on 2024-11-15 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_recipeingredient_measurement_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='measurement_name',
        ),
    ]
