# Generated by Django 5.0.3 on 2024-11-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_remove_ingredient_measurement_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='measurement_unit',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measurement_name',
            field=models.CharField(choices=[('шт', 'шт'), ('л', 'л'), ('л', 'л'), ('мл', 'мл'), ('гр', 'гр'), ('чайная ложка', 'чайная ложка'), ('столовая ложка', 'столовая ложка'), ('кг', 'кг'), ('мг', 'мг')], default='гр', max_length=50, verbose_name='Измерение'),
        ),
    ]
