# Generated by Django 4.2.16 on 2024-11-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_historicaluserrecipes_historicaluser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrecipe',
            name='status_site',
            field=models.CharField(choices=[('На модерации', 'На модерации'), ('Опубликован', 'Опубликован'), ('Отклонят', 'Отклонят'), ('Снят с публикации', 'Снят с публикации')], max_length=50, verbose_name='Статус на сайте'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='status_site',
            field=models.CharField(choices=[('На модерации', 'На модерации'), ('Опубликован', 'Опубликован'), ('Отклонят', 'Отклонят'), ('Снят с публикации', 'Снят с публикации')], max_length=50, verbose_name='Статус на сайте'),
        ),
    ]
