# Generated by Django 4.2.16 on 2024-11-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_alter_historicalrecipe_status_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.RecipeIngredient', to='recipes.ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_name',
            field=models.CharField(choices=[('шт', 'шт'), ('л', 'л'), ('мл', 'мл'), ('гр', 'гр'), ('чайная ложка', 'чайная ложка'), ('столовая ложка', 'столовая ложка'), ('кг', 'кг'), ('мг', 'мг')], default='гр', max_length=50, verbose_name='Измерение'),
        ),
    ]
