# Generated by Django 4.2.16 on 2024-12-15 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_alter_historicalrecipecomment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipecomment',
            options={'ordering': ['created_at'], 'verbose_name': 'Комментарий к рецепту', 'verbose_name_plural': 'Комментарии к рецептам'},
        ),
    ]
